
version: "3.8"
services:
  etherpad:
    image: etherpad.azurecr.io/etherpad
    container_name: etherpad
    restart: always
    build:
      context: ./etherpad  
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    networks:
      - my_network

  react-app:
    image: etherpad.azurecr.io/react-app
    container_name: react-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
       - ./:/app
       - /node_modules
    ports:
      - "3000:3000"
    environment:
       - CHOKIDAR_USEPOLLING=true
    networks:
      - my_network

  backend:  
    image: etherpad.azurecr.io/backend
    container_name: backend
    build:
      context: ./backend  
      dockerfile: Dockerfile
    ports:
      - "3001:3001"  
    depends_on:
      - react-app
    environment:
      - API_KEY=${API_KEY}
    networks:
      - my_network

  nginx:
    image: etherpad.azurecr.io/nginx
    container_name: nginx
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - my_network

networks:
  my_network:
