# # docker-compose.yml
# version: "3.8"
# services:
#    frontend:
#      build:
#        context: .
#        dockerfile: Dockerfile
#      volumes:
#        - ./:/app
#       #  - /node_modules
#      ports:
#        - 3000:3000
#      environment:
#        - CHOKIDAR_USEPOLLING=true
version: "3.8"
services:
  etherpad:
    container_name: etherpad
    restart: always
    image: etherpad/etherpad:latest
    ports:
      - "9000:9001"
    environment:
      PORT: '9001'
    networks:
      - my_network

  react-app:
    container_name: react-app
    restart: always
    build:
      context: . # Directory where the React app is located
      dockerfile: Dockerfile
    volumes:
       - ./:/app
       - /node_modules
    ports:
      - "3000:3000"
    environment:
       - CHOKIDAR_USEPOLLING=true
    networks:
      - my_network

  backend:  
    container_name: backend
    build:
      context: ./backend  
      dockerfile: Dockerfile
    ports:
      - "3001:3001"  
    depends_on:
      - react-app
    environment:
      - API_KEY=${API_KEY}
    networks:
      - my_network

  nginx:
    container_name: nginx
    restart: always
    image: nginx:1.21-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - my_network

networks:
  my_network:
