# Use the official Etherpad image as the base image
FROM etherpad/etherpad:latest

# Expose the port on which Etherpad runs
EXPOSE 9001

# Set the environment variable for the Etherpad port
ENV PORT=9001
